# Generated by Django 5.0.6 on 2024-06-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                ("id_alerta", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(unique=True)),
                ("value", models.FloatField()),
                ("version", models.IntegerField()),
                (
                    "type",
                    models.TextField(
                        choices=[("BAJA", "BAJA"), ("MEDIA", "MEDIA"), ("ALTA", "ALTA")]
                    ),
                ),
                ("sended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
